:version: 1.0.0

= Karma Gradle Plugin

This Gradle plugin allows you to run Jasmine, Qunit, or Mocha tests using the Karma test runner.

== Getting Started

[source,gradle,subs='attributes']
----
plugins {
    id 'com.craigburke.karma' version '{version}'
}
----

== Tasks

The plugin adds the following tasks to your build:

|===

| *Task* | *Description* 

| karmaRun | Runs your tests

| karmaWatch | Runs your tests in watch mode

| karmaRefresh | Refresh the generated karma config file

| karmaClean | Deletes the karma config file and removes the dependencies

|===

== Configuration

You can use the same properties you'd set in your http://karma-runner.github.io/0.13/config/configuration-file.html[karma.config.js file] directly in *build.gradle*

[source,gradle,subs='attributes']
----
plugins {
    id 'com.craigburke.karma' version '{version}'
}

karma {
    basePath = 'src/assets' // <1>

    browsers = ['PhantomJS'] // <2>
    frameworks = ['jasmine'] // <3>
    reporters = ['junit'] // <4>

    files = [ // <5>
        'bower/angular/angular.js',
        '**/!(*.spec).js',
        '**/*.spec.js'
    ]

    exclude = ['jquery.js'] // <6>
}
----
<1> Optional base path for relative paths (like files or excludes).
<2> Runs tests in the browsers listed here (launcher dependencies are included). Possible values: PhantomJS, Firefox, Chrome, ChromeCanary, Opera, Internet Explorer, Safari
<3> Uses the listed frameworks and installs the dependencies. Possible values: jasmine, mocha, qunit.
<4> Add additional reporters (also installs needed dependencies). Possible values: progress, junit, coverage, growl, teamcity
<5> Files for karma to load
<6> Exclusions for files

NOTE: if *basePath* is not set, it defaults to `src/assets` or `grails-app/assets` if the Grails plugin is applied.

=== Advanced configuration

In addition to the properties listed above, you can also include set other Karma properties through the DSL.
 
[source,gradle,subs='attributes']
----
karma {
    colors = true
    junitReporter = [outputDir: 'test-dir' ]
}
----
<1> *additional* is a map that allows additional properties to be added to Karma's configuration.